function vf = vf_sorted(obj,temp,cs)

  qr = obj.progress_rate(temp,cs);

  % disp('size(temp) = ')
  % disp(size(temp))
  % disp('size(qr) = ')
  % disp(size(qr))

  vf = [sum(sort([-qr(:,1),-qr(:,2),-qr(:,4)],2,'ComparisonMethod','abs'),2), ...
        sum(sort([qr(:,1),qr(:,2),2*qr(:,4),-qr(:,5),-qr(:,6)],2,'ComparisonMethod','abs'),2), ...
        sum(sort([-qr(:,1),-qr(:,3),-qr(:,5)],2,'ComparisonMethod','abs'),2), ...
        sum(sort([qr(:,1),-qr(:,2),2*qr(:,3),qr(:,5),-qr(:,6)],2,'ComparisonMethod','abs'),2), ...
        sum(sort([qr(:,2),-qr(:,3),qr(:,6)],2,'ComparisonMethod','abs'),2), ...
        zeros(length(temp),1)];
  % vf = [sum(sort([-qr(:,1),-qr(:,2),-qr(:,4)],'ComparisonMethod','abs')), ...
  %       sum(sort([qr(:,1),qr(:,2),2*qr(:,4),-qr(:,5),-qr(:,6)],'ComparisonMethod','abs')), ...
  %       sum(sort([-qr(:,1),-qr(:,3),-qr(:,5)],'ComparisonMethod','abs')), ...
  %       sum(sort([qr(:,1),-qr(:,2),2*qr(:,3),qr(:,5),-qr(:,6)],'ComparisonMethod','abs')), ...
  %       sum(sort([qr(:,2),-qr(:,3),qr(:,6)],'ComparisonMethod','abs')), ...
  %       0.0];
end
