function [p_sol,fval,exitflag] = tboa(obj,objfun,nonlcon,p0)
  arguments
    obj
    objfun = @(p) obj.tboa_objfun([0,1],p)
    nonlcon = @(p) obj.tboa_nonlcon(1,[0,1],p)
    p0 = obj.rand_init_val()
  end

  options = optimoptions('fmincon','Display','iter' ...
                        ... % ,'Algorithm','sqp' ...
                        ,'StepTolerance',1e-15 ...
                        ... % ,'MaxFunEvals',50000 ...
                        ... % ,'TolX',1e-10 ...
                        ... % ,'TolCon',1e-6 ...
                        );

  %,'Algorithm','sqp');%,'MaxFunEvals',50000);
  [p_sol,fval,exitflag] = fmincon(objfun, p0, ...
                                  obj.tboa_A, obj.tboa_b, ...
                                  obj.tboa_Aeq, obj.tboa_beq, ...
                                  obj.tboa_lb, obj.tboa_ub, ...
                                  nonlcon, ...
                                  options);
end
